use_frameworks!
platform :ios, '10.0'

target 'PunkAPI_Example' do
  pod 'PunkAPI', :path => '../'
  pod 'PunkAPI/PromiseKit', :path => '../'
  pod 'PunkAPI/RxSwift', :path => '../'

  target 'PunkAPI_Tests' do
    inherit! :search_paths

    
  end
end
